Traceback (most recent call last):
  File "test/run/t274.py", line 8, in <module>
    raise ValueError, "no such test method in %s: %s" % (x.__class__, methodName)
ValueError: no such test method in __main__.X: wee
